a= int(input("Enter a:"))
b= int(input("Enter b:"))
print("sum is :",a+b)
print("Difference is :",a-b)
print("Product is :",a*b)
print("Integer division is :",a//b)
print("Float division is :",a/b)
print("Modulo is :",a%b)
print("Power is :",a**b)